# R8/ProGuard rules for Arcana.
#
# Most of our libraries (Compose, Hilt, Room, Coil) ship their own consumer
# rules and don't need anything here. The fragile bit is kotlinx.serialization:
# our JSON DTOs use field names that R8 would otherwise rename, breaking the
# parsing of cards.json / spreads.json. The plugin generates @Serializer(forClass)
# stubs which R8 can detect, but we belt-and-suspenders the source-of-truth DTOs.

# --- kotlinx.serialization plumbing -----------------------------------------
# Keep the synthetic .Companion / $$serializer classes the plugin generates.
-keepclasseswithmembers class **$$serializer { *; }
-keepclassmembers class **.Companion {
    kotlinx.serialization.KSerializer serializer(...);
}
# If there's no Companion in a serializable class, look for the plain
# .serializer() function generated by the plugin.
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
    static <1>$Companion Companion;
}

# --- Our own JSON DTOs ------------------------------------------------------
# These are the data classes loaded from cards.json and spreads.json. Their
# field names ARE the JSON schema, so they must not be renamed.
-keep class com.arcana.core.data.source.** { *; }

# --- Domain enums -----------------------------------------------------------
# Enum names appear in DataStore preferences (AiBackendType, ThemeMode, etc.)
# and in Room columns (ReadingKind, Orientation). Keep their string identity.
-keepnames enum com.arcana.core.domain.model.** { *; }

# --- Reflection-free configuration ------------------------------------------
# Standard Kotlin metadata so reflection-light operations still resolve.
-keep class kotlin.Metadata { *; }

# --- Strip log calls in release ---------------------------------------------
# android.util.Log calls evaluate their message arguments even when filtered.
# Stripping them at compile time removes that overhead entirely.
-assumenosideeffects class android.util.Log {
    public static *** v(...);
    public static *** d(...);
    public static *** i(...);
}
